package vg.civcraft.mc.contraptions.gadgets;

import vg.civcraft.mc.contraptions.ContraptionsPlugin;
import vg.civcraft.mc.contraptions.contraptions.Contraption;
import vg.civcraft.mc.contraptions.utility.Resource;
import vg.civcraft.mc.contraptions.utility.InventoryHelpers;
import java.util.Set;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.Plugin;
import org.bukkit.scheduler.BukkitRunnable;
import org.bukkit.scheduler.BukkitTask;
import org.json.JSONObject;

/**
 * A gadget which will converts between ItemStacks and resources
 *
 * This can be used for things such as powering Contraptions via the items they
 * contain within them
 *
 * It can be imported from a JSON object in the following format
 * <pre>
 * {
 *   "inputs":
 *     [{
 *         "material": "MATERIAL_NAME",
 *         "amount": 1,
 *         "durability": 0,
 *         "name": "DISPLAY_NAME",
 *         "lore": "LORE"
 *       },...
 *       }],
 *   "conversion": 1
 * }
 * </pre>
 */
public class ConversionGadget {

    //Converted ItemStacks
    Set<ItemStack> itemStacks;
    //The Exchange rate between ItemStacks and Resources
    double conversion;

    /**
     * Creates a ConversionGadget
     *
     * @param itemStacks The ItemStacks consumed
     * @param conversion The amount of resource generated by the ItemStacks
     */
    public ConversionGadget(Set<ItemStack> itemStacks, double conversion) {
        this.itemStacks = itemStacks;
        this.conversion = conversion;
    }

    /**
     * Given an inventory checks if there are enough ItemStacks to generate
     * amount of resource
     *
     * @param amount The amount of resource to generate
     * @param inventory The inventory to pull ItemStacks from
     * @return Check if there are enough ItemStacks to generate amount
     */
    public boolean canConvertToResource(double amount, Inventory inventory) {
        double amountAvailible = InventoryHelpers.amountAvailable(inventory, itemStacks);
        return amountAvailible * conversion >= amount;
    }

    /**
     * Consumes ItemSets to generate a resource
     *
     * @param amount Amount of resource to produce
     * @param inventory The inventory from which to draw ItemStacks
     * @param resource The resource to generate
     * @return If there were enough ItemStacks to generate amount
     */
    public boolean convertToResource(double amount, Inventory inventory, Resource resource) {
        int itemAmount = (int) Math.ceil(amount / conversion);
        return convertToResource(itemAmount, inventory, resource);
    }

    public boolean convertToResrouce(int itemAmount, Inventory inventory, Resource resource) {
        if (InventoryHelpers.removeMultiple(inventory, itemStacks, itemAmount)) {
            resource.change(itemAmount * conversion);
            return true;
        }
        return false;
    }

    /**
     * Consumes a resource to generate ItemStacks
     *
     * @param resource Resource to consume
     * @param inventory Inventory to place ItemStacks in
     * @param amount Amount of resource to consume
     */
    public void convertToItemStacks(Resource resource, Inventory inventory, double amount) {
        int numberOfSets = (int) Math.ceil(amount / conversion);
        InventoryHelpers.putMultiple(inventory, itemStacks, numberOfSets);
        resource.change(numberOfSets * conversion);

    }

    /**
     * Attempts to convert to a resource until that resource exceeds amount
     *
     * @param resource Resource to convert to
     * @param inventory Inventory to get ItemStacks from
     * @param amount Amount which the resource should exceed
     * @return If the resource exceeds the amount
     */
    public boolean convertUpToResource(Resource resource, Inventory inventory, double amount) {
        double resourceRequired = amount - resource.get();
        if (resourceRequired <= 0) {
            return true;
        }
        int itemsRequired = (int) Math.ceil(resourceRequired / conversion);
        int itemsAvailable = InventoryHelpers.amountAvailable(inventory, itemStacks);
        if (itemsAvailable >= itemsRequired) {
            convertToResource(itemsRequired, inventory, resource);
            return true;
        } else {
            convertToResource(itemsAvailable, inventory, resource);
            return false;
        }
    }

    /**
     * Converts resource to ItemStacks until the resource is below amount
     *
     * @param resource Resource to convert
     * @param inventory Inventory to place ItemStacks in
     * @param amount Amount to drop resource below
     */
    public void ConvertDownToResource(Resource resource, Inventory inventory, double amount) {
        if (resource.get() > amount) {
            convertToItemStacks(resource, inventory, resource.get() - amount);
        }
        //Required becuase the conversion gadget will round down, failing to convert to the last ItemStack
        if (resource.get() > amount) {
            convertToItemStacks(resource, inventory, conversion);
        }
    }

    public double getConversionRate() {
        return conversion;
    }

    /**
     * Gets a ConvertToItemStackRunnable
     *
     * @param contraption Associated contraption
     * @param resource Associated resource
     * @return A BukkitTask associated with a runnable of this ConversionGadget
     */
    public BukkitTask getConvertToItemStacksRunnable(Contraption contraption, Resource resource) {
        return (new ConvertToItemStacksRunnable(contraption, resource)).runTaskTimerAsynchronously(ContraptionsPlugin.getContraptionPlugin(), 1000, 1000);
    }

    public class ConvertToItemStacksRunnable extends BukkitRunnable {

        Contraption contraption;
        Resource resource;

        /**
         * The ConversionGadget runnable associated with converting Resources to
         * ItemStacks
         *
         * @param contraption Contraption associated with runnable
         * @param resource Resource associated with runnable
         */
        public ConvertToItemStacksRunnable(Contraption contraption, Resource resource) {
            this.contraption = contraption;
            this.resource = resource;
        }

        /**
         * Schedules the task and grows the resource to the delay
         *
         * @param plugin The Contraptions Plugin
         * @param delay The delay until the task is executed in ticks
         * @param period The period in ticks with which the task is executed
         *
         * @return A Task associated with this runnable
         */
        @Override
        public synchronized BukkitTask runTaskTimer(Plugin plugin, long delay, long period) throws IllegalArgumentException, IllegalStateException {
            run();
            return super.runTaskTimer(plugin, delay, period);
        }

        /**
         * Grows the resource
         */
        @Override
        public void run() {
            convertToItemStacks(resource, contraption.getInventory(), resource.get());
        }
    }

    /**
     * Imports a ConversionGadget from a JSONObject
     *
     * @param jsonObject The JSONObject containing the information
     * @return A ConversionGadget with the properties contained in the
     * JSONObject
     */
    public static ConversionGadget fromJSON(JSONObject jsonObject) {
        Set<ItemStack> itemStacks = InventoryHelpers.fromJSON(jsonObject.getJSONArray("inputs"));
        double conversion = jsonObject.getDouble("conversion");
        return new ConversionGadget(itemStacks, conversion);
    }
}
